import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import styles from "@/app/layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className={styles.container}>
          <header>
            <Link href={"/"}>👕 Shopping Mall 👔</Link>
          </header>
          <main>{children}</main>
          <footer>
            Copyright © 2025 <b>fakeshop</b>. All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
